apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
spec:
  containers:
    - name: counter
      image: ghcr.io/subicura/counter:lastest
      env:
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis