apiVersion: apps/v1
kind: Deployment
metadata: 
    name: my-app-mysql
    labels: 
        app: my-app
spec: 
    selector: 
        matchLabels: 
            app: my-app
            tier: mysql
    template: 
        metadata: 
            labels: 
                app: my-app
                tier: mysql
        spec: 
            containers: 
                - image: mariadb:10.7
                  name: mysql
                  env: 
                      - name: MYSQL_DATABASE
                        value: my-app
                      - name: MYSQL_ROOT_PASSWORD
                        value: password
                  ports: 
                      - containerPort: 3306
                        name: mysql
---
apiVersion: v1
kind: Service
metadata: 
    name: my-app-mysql
    labels: 
        app: my-app
spec: 
    ports: 
        - port: 3306
    selector: 
        app: my-app
        tier: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: my-app
    labels: 
        app: my-app
spec:
    replicas: 5
    selector: 
        matchLabels: 
            app: my-app
            tier: frontend
    template: 
        metadata: 
            labels: 
                app: my-app
                tier: frontend
        spec: 
            containers: 
                - image: wordpress:5.9.1-php8.1-apache
                  name: my-app
                  env: 
                      - name: WORD_PRESS_DB_HOST
                        value: my-app-mysql
                      - name: WORD_PRESS_DB_NAME
                        value: my-app
                      - name: WORD_PRESS_DB_USER
                        value: root
                      - name: WORD_PRESS_DB_PASSWORD
                        value: password
                  ports: 
                      - containerPort: 80
                        name: my-app

---
apiVersion: v1
kind: Service
metadata: 
    name: my-app
spec:
    type: NodePort
    ports: 
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30080
    selector:
        app: my-app
        tier: frontend
          